[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "v-epsilon"
version = "0.1.0"
description = "A capstone chatbot project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-openai",
    "langchain-anthropic",
    "langchain-google-genai",
    "langchain-groq",
    "langchain-community",
]

[tool.hatch.build.targets.wheel]
packages = ["src/v_epsilon"]
